### ISSUE TITLE
rake redmine_leaves:populate_time_spent warnings

### ISSUE THREAD

**Issue by radist** [arkhitech/redmine_leaves#74]
`$ bundle exec rake redmine_leaves:populate_time_spent RAILS_ENV=production
./plugins/redmine_login_audit/config/wice_grid_config.rb:5: warning: already initialized constant Wice::Defaults::PER_PAGE
./plugins/redmine_leaves/config/wice_grid_config.rb:4: warning: previous definition of PER_PAGE was here
./plugins/redmine_login_audit/config/wice_grid_config.rb:8: warning: already initialized constant Wice::Defaults::ORDER_DIRECTION
./plugins/redmine_leaves/config/wice_grid_config.rb:7: warning: previous definition of ORDER_DIRECTION was here
./plugins/redmine_login_audit/config/wice_grid_config.rb:13: warning: already initialized constant Wice::Defaults::GRID_NAME
./plugins/redmine_leaves/config/wice_grid_config.rb:12: warning: previous definition of GRID_NAME was here
./plugins/redmine_login_audit/config/wice_grid_config.rb:17: warning: already initialized constant Wice::Defaults::REUSE_LAST_COLUMN_FOR_FILTER_ICONS
./plugins/redmine_leaves/config/wice_grid_config.rb:16: warning: previous definition of REUSE_LAST_COLUMN_FOR_FILTER_ICONS was here
./plugins/redmine_login_audit/config/wice_grid_config.rb:20: warning: already initialized constant Wice::Defaults::CUSTOM_FILTER_ALL_LABEL
./plugins/redmine_leaves/config/wice_grid_config.rb:19: warning: previous definition of CUSTOM_FILTER_ALL_LABEL was here
./plugins/redmine_login_audit/config/wice_grid_config.rb:23: warning: already initialized constant Wice::Defaults::DEFAULT_TABLE_CLASSES
./plugins/redmine_leaves/config/wice_grid_config.rb:22: warning: previous definition of DEFAULT_TABLE_CLASSES was here
./plugins/redmine_login_audit/config/wice_grid_config.rb:26: warning: already initialized constant Wice::Defaults::ALLOW_MULTIPLE_SELECTION
./plugins/redmine_leaves/config/wice_grid_config.rb:25: warning: previous definition of ALLOW_MULTIPLE_SELECTION was here
./plugins/redmine_login_audit/config/wice_grid_config.rb:29: warning: already initialized constant Wice::Defaults::SHOW_UPPER_PAGINATION_PANEL
./plugins/redmine_leaves/config/wice_grid_config.rb:28: warning: previous definition of SHOW_UPPER_PAGINATION_PANEL was here
./plugins/redmine_login_audit/config/wice_grid_config.rb:32: warning: already initialized constant Wice::Defaults::ENABLE_EXPORT_TO_CSV
./plugins/redmine_leaves/config/wice_grid_config.rb:31: warning: previous definition of ENABLE_EXPORT_TO_CSV was here
./plugins/redmine_login_audit/config/wice_grid_config.rb:35: warning: already initialized constant Wice::Defaults::CSV_FIELD_SEPARATOR
./plugins/redmine_leaves/config/wice_grid_config.rb:34: warning: previous definition of CSV_FIELD_SEPARATOR was here
./plugins/redmine_login_audit/config/wice_grid_config.rb:42: warning: already initialized constant Wice::Defaults::SHOW_FILTER
./plugins/redmine_leaves/config/wice_grid_config.rb:41: warning: previous definition of SHOW_FILTER was here
./plugins/redmine_login_audit/config/wice_grid_config.rb:45: warning: already initialized constant Wice::Defaults::AUTO_RELOAD
./plugins/redmine_leaves/config/wice_grid_config.rb:44: warning: previous definition of AUTO_RELOAD was here
./plugins/redmine_login_audit/config/wice_grid_config.rb:49: warning: already initialized constant Wice::Defaults::STRING_MATCHING_OPERATOR
./plugins/redmine_leaves/config/wice_grid_config.rb:48: warning: previous definition of STRING_MATCHING_OPERATOR was here
./plugins/redmine_login_audit/config/wice_grid_config.rb:56: warning: already initialized constant Wice::Defaults::STRING_MATCHING_OPERATORS
./plugins/redmine_leaves/config/wice_grid_config.rb:55: warning: previous definition of STRING_MATCHING_OPERATORS was here
./plugins/redmine_login_audit/config/wice_grid_config.rb:67: warning: already initialized constant Wice::Defaults::NEGATION_IN_STRING_FILTERS
./plugins/redmine_leaves/config/wice_grid_config.rb:66: warning: previous definition of NEGATION_IN_STRING_FILTERS was here
./plugins/redmine_login_audit/config/wice_grid_config.rb:97: warning: already initialized constant Wice::Defaults::ALLOW_SHOWING_ALL_QUERIES
./plugins/redmine_leaves/config/wice_grid_config.rb:74: warning: previous definition of ALLOW_SHOWING_ALL_QUERIES was here
./plugins/redmine_login_audit/config/wice_grid_config.rb:101: warning: already initialized constant Wice::Defaults::START_SHOWING_WARNING_FROM
./plugins/redmine_leaves/config/wice_grid_config.rb:77: warning: previous definition of START_SHOWING_WARNING_FROM was here
./plugins/redmine_login_audit/config/wice_grid_config.rb:109: warning: already initialized constant Wice::Defaults::QUERY_STORE_MODEL
./plugins/redmine_leaves/config/wice_grid_config.rb:86: warning: previous definition of QUERY_STORE_MODEL was here
./plugins/redmine_login_audit/config/wice_grid_config.rb:119: warning: already initialized constant Wice::Defaults::HELPER_STYLE
./plugins/redmine_leaves/config/wice_grid_config.rb:95: warning: previous definition of HELPER_STYLE was here
./plugins/redmine_login_audit/config/wice_grid_config.rb:123: warning: already initialized constant Wice::Defaults::DATETIME_FORMAT
./plugins/redmine_leaves/config/wice_grid_config.rb:99: warning: previous definition of DATETIME_FORMAT was here
./plugins/redmine_login_audit/config/wice_grid_config.rb:127: warning: already initialized constant Wice::Defaults::DATE_FORMAT
./plugins/redmine_leaves/config/wice_grid_config.rb:103: warning: previous definition of DATE_FORMAT was here
./plugins/redmine_login_audit/config/wice_grid_config.rb:131: warning: already initialized constant Wice::Defaults::DATE_FORMAT_JQUERY
./plugins/redmine_leaves/config/wice_grid_config.rb:107: warning: previous definition of DATE_FORMAT_JQUERY was here
./plugins/redmine_login_audit/config/wice_grid_config.rb:138: warning: already initialized constant Wice::Defaults::DATETIME_PARSER
./plugins/redmine_leaves/config/wice_grid_config.rb:114: warning: previous definition of DATETIME_PARSER was here
./plugins/redmine_login_audit/config/wice_grid_config.rb:151: warning: already initialized constant Wice::Defaults::DATEPICKER_YEAR_RANGE
./plugins/redmine_leaves/config/wice_grid_config.rb:146: warning: previous definition of DATEPICKER_YEAR_RANGE was here
./plugins/redmine_login_audit/config/wice_grid_config.rb:158: warning: already initialized constant Wice::Defaults::DATE_PARSER
./plugins/redmine_leaves/config/wice_grid_config.rb:129: warning: previous definition of DATE_PARSER was here
./plugins/redmine_login_audit/config/wice_grid_config.rb:167: warning: already initialized constant Wice::Defaults::CALENDAR_ICON
./plugins/redmine_leaves/config/wice_grid_config.rb:138: warning: previous definition of CALENDAR_ICON was here
./plugins/redmine_login_audit/config/wice_grid_config.rb:170: warning: already initialized constant Wice::Defaults::POPUP_PLACEMENT_STRATEGY
./plugins/redmine_leaves/config/wice_grid_config.rb:141: warning: previous definition of POPUP_PLACEMENT_STRATEGY was here
`

Environment:
  Redmine version                3.3.1.stable
  Ruby version                   2.3.3-p222 (2016-11-21) [x86_64-linux]
  Rails version                  4.2.7.1
  Environment                    production
  Database adapter               PostgreSQL
SCM:
  Git                            2.7.4
  Filesystem                     
Redmine plugins:
  additionals                    2.0.0
  autowatch                      0.2.0
  clipboard_image_paste          1.10
  collapsed_journals             0.0.3
  issue_hot_buttons              0.4.4
  periodictask                   3.1.1
  progressive_projects_list      3.0.1
  projects_show                  0.0.3
  redmine__select2               1.1.0
  redmine_agile                  1.4.1
  redmine_attach_by_url          1.0.2
  redmine_bitbucket              1.0.0
  redmine_chat_telegram          1.6.1
  redmine_checklists             3.1.5
  redmine_ckeditor               1.1.4
  redmine_codebutton             0.1.0
  redmine_contacts               4.0.4
  redmine_contacts_helpdesk      3.0.1
  redmine_contacts_invoices      4.1.1
  redmine_custom_css             0.1.6
  redmine_custom_workflows       0.1.6
  redmine_dashboard              2.7.1
  redmine_default_assign         0.6
  redmine_digest                 1.1.0
  redmine_editauthor             0.11.0
  redmine_email_images           0.2.0
  redmine_email_logs             0.0.1
  redmine_finance                2.1.0
  redmine_gist                   0.1.0
  redmine_gitlab_hook            0.1.3
  redmine_impersonate            0.10.0
  redmine_intouch                0.6.1
  redmine_issue_completion       0.0.2
  redmine_issue_favicon          0.0.1
  redmine_issue_history_filter   0.0.1
  redmine_issue_templates        0.1.3
  redmine_jstoolbar_ext          0.2.1
  redmine_jstoolbar_ext_images   0.3.1
  redmine_keyboard_shortcuts     0.0.1
  redmine_knowledgebase          3.2.1
  redmine_leaves                 0.1.0
  redmine_lightbox2              0.3.1
  redmine_login_audit            0.3.1
  redmine_macros                 0.0.1
  redmine_mail_reminder          3.0.0.0001
  redmine_mentions               0.0.1
  redmine_move_comments          0.0.2
  redmine_my_page                0.1.10
  redmine_one_issue_in_process_only 0.0.4
  redmine_people                 1.2.0
  redmine_percent_done           1.1.0
  redmine_project_alias_2        1.0.2
  redmine_recurring_tasks        0.0.2
  redmine_scheduling_poll        2.0.0
  redmine_shared_api             0.0.2
  redmine_sidekiq                2.1.0
  redmine_silencer               0.4.1
  redmine_slack                  0.2
  redmine_spent_time             3.1.2
  redmine_spent_time_curve       0.0.1
  redmine_tags                   3.1.1
  redmine_telegram_common        0.0.15
  redmine_theme_changer          0.2.0
  redmine_webhook                0.0.2
  redmine_workflow_hidden_fields 0.3.0
  sidebar_hide                   0.0.7
  subtask_list_columns           0.0.3
  ttm                            0.2.0
  unread_issues                  2.1.0
  vault                          0.3.0

**Comment by hishammalik** [comment]
looks like wicegrid is also used in another plugin 'redmine_login_audit' plugin that you're using. The warnings can be ignored for now, without any issues.
